server:
  port: 8088

spring:
  datasource:
    url: jdbc:mysql://kol0i6elxdrgp9ey:caskofnxovv5r1vw@pxukqohrckdfo4ty.cbetxkdyhwsb.us-east-1.rds.amazonaws.com:3306/uxgfhgxyelocad7d?reconnect=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: kol0i6elxdrgp9ey
    password: caskofnxovv5r1vw

  spring:

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  messages:
    basename: i18n/messages
    encoding: UTF-8
    default-locale: en

api:
  prefix: api/v1

jwt:
  expiration: 2592000
    #30 days = 30 * 24 * 60 * 60
  secretKey: XsxIrJU5YktIqIJDJr7sYUrUYx+joroTKsMAwjqigm8=


